# Generated by Django 5.2.6 on 2026-02-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0067_remove_nixchannel_pgpubsub_ae5b1_and_more'),
        ('webview', '0005_profile_auto_subscribe_to_maintained_packages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webview.notification')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared.cvederivationclusterproposal')),
            ],
            options={
                'abstract': False,
            },
            bases=('webview.notification',),
        ),
    ]
