# Generated by Django 5.2.9 on 2026-02-06 17:11

from django.db import migrations, models


def populate_package_names(apps, schema_editor):
    NixPackage = apps.get_model('shared', 'NixPackage')
    NixDerivation = apps.get_model('shared', 'NixDerivation')

    attribute_paths = NixDerivation.objects.values_list('attribute', flat=True).distinct()

    packages = (NixPackage(name=attr) for attr in attribute_paths)
    NixPackage.objects.bulk_create(packages, batch_size=5000)


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0067_remove_nixchannel_pgpubsub_ae5b1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NixPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('derivations', models.ManyToManyField(related_name='package', to='shared.nixderivation')),
            ],
        ),
        migrations.RunPython(populate_package_names, migrations.RunPython.noop),
    ]
