# Generated by Django 5.2.9 on 2026-02-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0068_alter_nixmaintainer_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nixderivation',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='nixderivationoutput',
            name='outputs',
        ),
        migrations.RemoveField(
            model_name='nixderivation',
            name='outputs',
        ),
        migrations.DeleteModel(
            name='NixDerivationDependencyThrough',
        ),
        migrations.DeleteModel(
            name='NixDerivationOutput',
        ),
        migrations.DeleteModel(
            name='NixOutput',
        ),
        migrations.DeleteModel(
            name='NixStorePathOutput',
        ),
    ]
