# Generated by Django 5.2.14 on 2026-06-26 22:50

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0097_nixevaluation_branch'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixchannel',
            name='pgpubsub_3c4a2',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixchannel',
            name='pgpubsub_f33a1',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsbranch',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_e8312', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixpkgsBranch"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_e8312\', payload);\n        \n            perform pg_notify(\'pgpubsub_e8312\', payload::text);\n            RETURN NEW;\n        ', hash='3ff58282b009e2375853065cd358fe72e9f4b424', operation='INSERT', pgid='pgtrigger_pgpubsub_e8312_36547', table='shared_nixpkgsbranch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsbranch',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_f3467', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixpkgsBranch"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_f3467\', payload);\n        \n            perform pg_notify(\'pgpubsub_f3467\', payload::text);\n            RETURN NEW;\n        ', hash='53b81f4834398baa28e4dda1a0b93b4fc9f96d8c', operation='UPDATE', pgid='pgtrigger_pgpubsub_f3467_cc4ab', table='shared_nixpkgsbranch', when='AFTER')),
        ),
    ]
